/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DayMeal {
  'day' : string,
  'breakfast' : string,
  'lunch' : string,
  'snacks' : string,
  'dinner' : string,
}
export type DietCondition = { 'CVD' : null } |
  { 'PCOS' : null } |
  { 'WeightGain' : null } |
  { 'WeightLoss' : null } |
  { 'Diabetes' : null };
export interface DietPlan {
  'id' : bigint,
  'mealTimingTips' : string,
  'name' : string,
  'overview' : string,
  'foodsToAvoid' : Array<string>,
  'recommendedFoods' : Array<string>,
  'mealPlan' : Array<DayMeal>,
  'condition' : DietCondition,
}
export interface Recipe {
  'id' : bigint,
  'fat' : bigint,
  'carbs' : bigint,
  'calories' : bigint,
  'name' : string,
  'description' : string,
  'conditionTags' : Array<DietCondition>,
  'instructions' : Array<string>,
  'imageUrl' : string,
  'prepTime' : bigint,
  'ingredients' : Array<string>,
  'protein' : bigint,
}
export interface _SERVICE {
  'getAllDietPlans' : ActorMethod<[], Array<DietPlan>>,
  'getAllRecipes' : ActorMethod<[], Array<Recipe>>,
  'getDietPlanByCondition' : ActorMethod<[DietCondition], [] | [DietPlan]>,
  'getRecipeById' : ActorMethod<[bigint], [] | [Recipe]>,
  'getRecipesByCondition' : ActorMethod<[DietCondition], Array<Recipe>>,
  'initializeData' : ActorMethod<[], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];