/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const DayMeal = IDL.Record({
  'day' : IDL.Text,
  'breakfast' : IDL.Text,
  'lunch' : IDL.Text,
  'snacks' : IDL.Text,
  'dinner' : IDL.Text,
});
export const DietCondition = IDL.Variant({
  'CVD' : IDL.Null,
  'PCOS' : IDL.Null,
  'WeightGain' : IDL.Null,
  'WeightLoss' : IDL.Null,
  'Diabetes' : IDL.Null,
});
export const DietPlan = IDL.Record({
  'id' : IDL.Nat,
  'mealTimingTips' : IDL.Text,
  'name' : IDL.Text,
  'overview' : IDL.Text,
  'foodsToAvoid' : IDL.Vec(IDL.Text),
  'recommendedFoods' : IDL.Vec(IDL.Text),
  'mealPlan' : IDL.Vec(DayMeal),
  'condition' : DietCondition,
});
export const Recipe = IDL.Record({
  'id' : IDL.Nat,
  'fat' : IDL.Nat,
  'carbs' : IDL.Nat,
  'calories' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'conditionTags' : IDL.Vec(DietCondition),
  'instructions' : IDL.Vec(IDL.Text),
  'imageUrl' : IDL.Text,
  'prepTime' : IDL.Nat,
  'ingredients' : IDL.Vec(IDL.Text),
  'protein' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getAllDietPlans' : IDL.Func([], [IDL.Vec(DietPlan)], ['query']),
  'getAllRecipes' : IDL.Func([], [IDL.Vec(Recipe)], ['query']),
  'getDietPlanByCondition' : IDL.Func(
      [DietCondition],
      [IDL.Opt(DietPlan)],
      ['query'],
    ),
  'getRecipeById' : IDL.Func([IDL.Nat], [IDL.Opt(Recipe)], ['query']),
  'getRecipesByCondition' : IDL.Func(
      [DietCondition],
      [IDL.Vec(Recipe)],
      ['query'],
    ),
  'initializeData' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const DayMeal = IDL.Record({
    'day' : IDL.Text,
    'breakfast' : IDL.Text,
    'lunch' : IDL.Text,
    'snacks' : IDL.Text,
    'dinner' : IDL.Text,
  });
  const DietCondition = IDL.Variant({
    'CVD' : IDL.Null,
    'PCOS' : IDL.Null,
    'WeightGain' : IDL.Null,
    'WeightLoss' : IDL.Null,
    'Diabetes' : IDL.Null,
  });
  const DietPlan = IDL.Record({
    'id' : IDL.Nat,
    'mealTimingTips' : IDL.Text,
    'name' : IDL.Text,
    'overview' : IDL.Text,
    'foodsToAvoid' : IDL.Vec(IDL.Text),
    'recommendedFoods' : IDL.Vec(IDL.Text),
    'mealPlan' : IDL.Vec(DayMeal),
    'condition' : DietCondition,
  });
  const Recipe = IDL.Record({
    'id' : IDL.Nat,
    'fat' : IDL.Nat,
    'carbs' : IDL.Nat,
    'calories' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'conditionTags' : IDL.Vec(DietCondition),
    'instructions' : IDL.Vec(IDL.Text),
    'imageUrl' : IDL.Text,
    'prepTime' : IDL.Nat,
    'ingredients' : IDL.Vec(IDL.Text),
    'protein' : IDL.Nat,
  });
  
  return IDL.Service({
    'getAllDietPlans' : IDL.Func([], [IDL.Vec(DietPlan)], ['query']),
    'getAllRecipes' : IDL.Func([], [IDL.Vec(Recipe)], ['query']),
    'getDietPlanByCondition' : IDL.Func(
        [DietCondition],
        [IDL.Opt(DietPlan)],
        ['query'],
      ),
    'getRecipeById' : IDL.Func([IDL.Nat], [IDL.Opt(Recipe)], ['query']),
    'getRecipesByCondition' : IDL.Func(
        [DietCondition],
        [IDL.Vec(Recipe)],
        ['query'],
      ),
    'initializeData' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };