/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface DayMeal {
    day: string;
    breakfast: string;
    lunch: string;
    snacks: string;
    dinner: string;
}
export interface Recipe {
    id: bigint;
    fat: bigint;
    carbs: bigint;
    calories: bigint;
    name: string;
    description: string;
    conditionTags: Array<DietCondition>;
    instructions: Array<string>;
    imageUrl: string;
    prepTime: bigint;
    ingredients: Array<string>;
    protein: bigint;
}
export interface DietPlan {
    id: bigint;
    mealTimingTips: string;
    name: string;
    overview: string;
    foodsToAvoid: Array<string>;
    recommendedFoods: Array<string>;
    mealPlan: Array<DayMeal>;
    condition: DietCondition;
}
export enum DietCondition {
    CVD = "CVD",
    PCOS = "PCOS",
    WeightGain = "WeightGain",
    WeightLoss = "WeightLoss",
    Diabetes = "Diabetes"
}
export interface backendInterface {
    getAllDietPlans(): Promise<Array<DietPlan>>;
    getAllRecipes(): Promise<Array<Recipe>>;
    getDietPlanByCondition(condition: DietCondition): Promise<DietPlan | null>;
    getRecipeById(id: bigint): Promise<Recipe | null>;
    getRecipesByCondition(condition: DietCondition): Promise<Array<Recipe>>;
    initializeData(): Promise<void>;
}
import type { DayMeal as _DayMeal, DietCondition as _DietCondition, DietPlan as _DietPlan, Recipe as _Recipe } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getAllDietPlans(): Promise<Array<DietPlan>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDietPlans();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDietPlans();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllRecipes(): Promise<Array<Recipe>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRecipes();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRecipes();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDietPlanByCondition(arg0: DietCondition): Promise<DietPlan | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDietPlanByCondition(to_candid_DietCondition_n10(this._uploadFile, this._downloadFile, arg0));
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDietPlanByCondition(to_candid_DietCondition_n10(this._uploadFile, this._downloadFile, arg0));
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRecipeById(arg0: bigint): Promise<Recipe | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecipeById(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecipeById(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRecipesByCondition(arg0: DietCondition): Promise<Array<Recipe>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecipesByCondition(to_candid_DietCondition_n10(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecipesByCondition(to_candid_DietCondition_n10(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async initializeData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeData();
            return result;
        }
    }
}
function from_candid_DietCondition_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DietCondition): DietCondition {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_DietPlan_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DietPlan): DietPlan {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_Recipe_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Recipe): Recipe {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DietPlan]): DietPlan | null {
    return value.length === 0 ? null : from_candid_DietPlan_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Recipe]): Recipe | null {
    return value.length === 0 ? null : from_candid_Recipe_n7(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    mealTimingTips: string;
    name: string;
    overview: string;
    foodsToAvoid: Array<string>;
    recommendedFoods: Array<string>;
    mealPlan: Array<_DayMeal>;
    condition: _DietCondition;
}): {
    id: bigint;
    mealTimingTips: string;
    name: string;
    overview: string;
    foodsToAvoid: Array<string>;
    recommendedFoods: Array<string>;
    mealPlan: Array<DayMeal>;
    condition: DietCondition;
} {
    return {
        id: value.id,
        mealTimingTips: value.mealTimingTips,
        name: value.name,
        overview: value.overview,
        foodsToAvoid: value.foodsToAvoid,
        recommendedFoods: value.recommendedFoods,
        mealPlan: value.mealPlan,
        condition: from_candid_DietCondition_n4(_uploadFile, _downloadFile, value.condition)
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    fat: bigint;
    carbs: bigint;
    calories: bigint;
    name: string;
    description: string;
    conditionTags: Array<_DietCondition>;
    instructions: Array<string>;
    imageUrl: string;
    prepTime: bigint;
    ingredients: Array<string>;
    protein: bigint;
}): {
    id: bigint;
    fat: bigint;
    carbs: bigint;
    calories: bigint;
    name: string;
    description: string;
    conditionTags: Array<DietCondition>;
    instructions: Array<string>;
    imageUrl: string;
    prepTime: bigint;
    ingredients: Array<string>;
    protein: bigint;
} {
    return {
        id: value.id,
        fat: value.fat,
        carbs: value.carbs,
        calories: value.calories,
        name: value.name,
        description: value.description,
        conditionTags: from_candid_vec_n9(_uploadFile, _downloadFile, value.conditionTags),
        instructions: value.instructions,
        imageUrl: value.imageUrl,
        prepTime: value.prepTime,
        ingredients: value.ingredients,
        protein: value.protein
    };
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    CVD: null;
} | {
    PCOS: null;
} | {
    WeightGain: null;
} | {
    WeightLoss: null;
} | {
    Diabetes: null;
}): DietCondition {
    return "CVD" in value ? DietCondition.CVD : "PCOS" in value ? DietCondition.PCOS : "WeightGain" in value ? DietCondition.WeightGain : "WeightLoss" in value ? DietCondition.WeightLoss : "Diabetes" in value ? DietCondition.Diabetes : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DietPlan>): Array<DietPlan> {
    return value.map((x)=>from_candid_DietPlan_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Recipe>): Array<Recipe> {
    return value.map((x)=>from_candid_Recipe_n7(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DietCondition>): Array<DietCondition> {
    return value.map((x)=>from_candid_DietCondition_n4(_uploadFile, _downloadFile, x));
}
function to_candid_DietCondition_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DietCondition): _DietCondition {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DietCondition): {
    CVD: null;
} | {
    PCOS: null;
} | {
    WeightGain: null;
} | {
    WeightLoss: null;
} | {
    Diabetes: null;
} {
    return value == DietCondition.CVD ? {
        CVD: null
    } : value == DietCondition.PCOS ? {
        PCOS: null
    } : value == DietCondition.WeightGain ? {
        WeightGain: null
    } : value == DietCondition.WeightLoss ? {
        WeightLoss: null
    } : value == DietCondition.Diabetes ? {
        Diabetes: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
